### ISSUE TITLE
Use email as the primary user identifier

### ISSUE THREAD

**Issue by romainquellec** [CuistotduCoin/front#11]
![image.png](https://images.zenhubusercontent.com/5922dd6651aa2c30577efa4f/d5283eb9-0f19-42c0-bb25-c56e0cffa12b)

We want this.

The issue :
```
AddAdminToAdminGroup:
      DependsOn:
        - AdminUser
        - AdminGroup
      Type: AWS::Cognito::UserPoolUserToGroupAttachment
      Properties:
        GroupName: Admin
        Username: stephane@cuistotducoin.com
        UserPoolId: ${env:AWS_USERPOOL_ID}
```
Cannot use this code in `serverless.yml` since Cognito seems to use the user sub as its username instead of its email after the user has been created.

We need to make the change directly in the console and check out the CF file to see how its handled.

----
https://github.com/bsdkurt/aws-node-custom-user-pool
